import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import db from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/theme-provider";
import { twMerge } from "tailwind-merge";
import { Toaster } from "@/components/ui/sonner";
import AppStateProvider from "@/lib/providers/state-provider";
import { ModalProvider } from "@/lib/providers/modal-provider";
import { SupabaseUserProvider } from "@/lib/providers/user-provider";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(db);
  return (
    <html lang="en">
      <body className={twMerge("bg-background", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SupabaseUserProvider>
            <ModalProvider>
              <AppStateProvider>{children}</AppStateProvider>
              <Toaster />
            </ModalProvider>
          </SupabaseUserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
